### PR TITLE
Apollo Client Fixes & Cache

### PR DESCRIPTION
**Pull request by colbyfayock**
This simplifies the Apollo client creation which fixes caching issues and client reuse that  currently isnt working.

Seems to greatly improve load time after first page compile in dev mode, im guessing this will help overall build times too!

Helps address issues in https://github.com/colbyfayock/next-wordpress-starter/issues/168

### CODE REVIEW

**Comment by colbyfayock** [comment]
I need to still to a little homework on this, I'm getting a message in local dev:

```
Cache data may be lost when replacing the post field of a Query object.

To address this problem (which is not a bug in Apollo Client), either ensure all objects of type Post have an ID or a custom merge function, or define a custom merge function for the Query.post field, so InMemoryCache can safely merge these objects:

  existing: {"__typename":"Post","seo":{"__typename":"PostTypeSEO","canonical":"https://spacejelly.dev/posts/how-to-create-a-headless-wordpress-blog-with-next-js-wordpress-starter/","metaDesc":"","metaRobotsNofollow":"follow","metaRobotsNoindex":"index","opengraphAuthor":"","opengraphDescription":"Blogs are a great way to get down your thoughts to help others learn, keep track of progress, or even to help reinforce an idea to help yourself learn. WordPress is a popular blog platform that’s been around for a while and Next.js is a modern popular web framework for building React apps. How can […]","opengraphModifiedTime":"2021-04-30T12:17:53+00:00","opengraphPublishedTime":"2021-04-30T12:08:57+00:00","opengraphPublisher":"","opengraphTitle":"How to Create a Headless WordPress Blog with Next.js WordPress Starter - Next.js WordPress Starter","opengraphType":"article","readingTime":10,"title":"How to Create a Headless WordPress Blog with Next.js WordPress Starter - Next.js WordPress Starter","twitterDe
  incoming: {"__ref":"Post:cG9zdDoyMDA="}

For more information about these options, please refer to the documentation:

  * Ensuring entity objects have IDs: https://go.apollo.dev/c/generating-unique-identifiers
  * Defining custom merge functions: https://go.apollo.dev/c/merging-non-normalized-objects
```

**Comment by colbyfayock** [comment]
@GuilleAngulo fyi the PR for this. still gotta do a little for it, but if you wanted to poke at it

**Comment by colbyfayock** [comment]
alright @GuilleAngulo mind taking a look? should be good to go. it feels much snappier for me

**Review by GuilleAngulo — COMMENTED** [review]
It definitely performs faster! I think the code is ready to go, just little note on deleting the previous `apolloClient` variable at `apollo-client` and the `ApolloProvider` import on `_app` (eslint coming to the rescue 😆 )

**Comment by colbyfayock** [comment]
haha cool ill wait until you have your PR merged in and re-run linting on this before merging it

**Pull request merged**
