### PR TITLE
Fix infinite loading issue in src/lib/menu

### PR DESCRIPTION
**Pull request by alexandruvisan19**
Found the issue that occurs in https://github.com/colbyfayock/next-wordpress-starter/issues/307 and https://github.com/colbyfayock/next-wordpress-starter/issues/304.

### CODE REVIEW

**Comment by colbyfayock** [comment]
ah thanks @alexandruvisan19  - can you run `yarn format` locally and commit the changes?

**Comment by alexandruvisan19** [comment]
no problem, check now :)

**Comment by colbyfayock** [comment]
hey @alexandruvisan19 one more request

can you remove the package-lock.json from this PR? this project is currently using yarn and it's bad practice ot include both a package-lock.json and yarn.lock

if you know how, additionally itd be great if you could update your branch with `main` as tehre's a conflict with the yarn.lock file but if you're not sure how to do that i think i can fix that manually on my end

thanks

**Comment by colbyfayock** [comment]
thanks @alexandruvisan19 

@all-contributors please add @alexandruvisan19 for code

**Pull request merged**
