### PR TITLE
Change Search Index Compiler to use GraphQL

### LINKED ISSUE #66: Search index compiler should use GraphQL
We should update the search index compiler to use GraphQL to build the index to conform to the rest of the project

### PR DESCRIPTION
**Pull request by GuilleAngulo**
Fixes #66

### Description 
Changes the search index compiler plugin to use GraphQL. ~~It uses [graphql-request](https://github.com/prisma-labs/graphql-request).~~

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @GuilleAngulo looking good - ill spin it up to test out later today, curious though, did you try using Apollo for making the GraphQL request since we already have that available? i'm not as familiar with GraphQL yet so maybe theres a reason, but wondering if you tried just using that to avoid the additional dependency

**Comment by GuilleAngulo** [comment]
Hey! so my first though here was thinking the best approach and I ended up thinking on graphql-request (by Prisma team) because of its simplicity, lightweight and Node.js support, thinking that in this case it may fit like a good solution But you are right, maybe its a better idea to reuse a dependency that is already there. I will figure out how to do using Apollo and answer back to you 👍

**Comment by colbyfayock** [comment]
yeah thats fair, i dont know enough to say the strengths between the 2, i haven't used the new one you added, but i think in an ideal world we'd only have to wrangle a single tool through. thanks for taking a look

**Comment by GuilleAngulo** [comment]
Changed to use Apollo client 💪

**Comment by colbyfayock** [comment]
great job as usual, thanks @GuilleAngulo

**Pull request merged**
