### PR TITLE
Add a custom 404 page

### LINKED ISSUE #133: Page 404
## Description
Currently there isn't a custom 404 page and when landing at a page that doesn't exist, the default message is "An unexpected error has occurred.". In Next.js creating a custom 404 page is as easy as creating a `pages/404.js` file , so I thought it would be a nice adition. Anytime trying to access a page that doesn't exist, it will fall to that page.

About the content it could be a simple message like **Page Not Found** and a link to go back to homepage? What do you think?

### PR DESCRIPTION
**Pull request by GuilleAngulo**
### Description
It adds a custom 404 page, wrapped inside the Layout component with a homepage link. 

custom-404

#Fixes #133

### CODE REVIEW

**Comment by colbyfayock** [comment]
hm interesting enough it doesn't seem like it works as a staticly deployed page 🤔  https://deploy-preview-134--next-wordpress-starter.netlify.app/colby

i have a few thoughts here:
* maybe it doesn't work on deploy preview, if there's not an obvious solution we should probably just check before doing any additional work by merging it in
* the file is /404/index.html - netlify says it looks for 404.html, maybe it doesnt work because of that? though this blog post makes me feel like it should work https://www.netlify.com/blog/2020/12/08/making-a-custom-404-page-in-next.js/ if so we could consider adding a redirects file, something like `/404.html /404/index.html`, though idk if that would work

https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling

what do you think?

**Comment by colbyfayock** [comment]
to be clear the page itself works

https://deploy-preview-134--next-wordpress-starter.netlify.app/404/
https://deploy-preview-134--next-wordpress-starter.netlify.app/404/index.html
Interestingly this one too: https://deploy-preview-134--next-wordpress-starter.netlify.app/404.html

**Comment by GuilleAngulo** [comment]
That is weird ... dont know why is happening. Here in my machine is working  (in both modes:  **dev** and **build + start**)... As you say it may be the deploy preview or a redirection is needed ... not sure.

**Comment by colbyfayock** [comment]
lets give it a try! 🚢

**Pull request merged**
